### ISSUE TITLE
:question: More past data

### ISSUE THREAD

**Issue by abacao** [jesmak/euribor_rates#1]
Hello and thank you for your integration.

Is it possible to get older date than 1 year since today?

If so, how? Could that be a custom field like "Data since Jan 2022" (example)?

Thanks

**Comment by jesmak** [comment]
Hey! It's possible to get any number of days, as long as they are available in the data source this integration is using (euribor-rates.eu). I tested with 700 days and there was no issue. You just define the number of days you want to retrieve when configuring the integration. If you are using my example configuration for ApexCharts, remember to update the graphspan field to match the number of days you want to show.
